# Generated by Django 3.2.2 on 2021-07-18 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwapperNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(protocol='ipv4')),
                ('threads', models.IntegerField(default=0)),
                ('cpu', models.FloatField(default=0)),
                ('ram', models.FloatField(default=0)),
                ('disk', models.FloatField(default=0)),
            ],
        ),
    ]
