# Generated by Django 3.2.2 on 2021-07-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swappernode',
            name='max_threads',
            field=models.IntegerField(default=500),
        ),
    ]
