# Generated by Django 3.2.2 on 2021-07-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamaccount',
            name='steam_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
