# Generated by Django 3.2.2 on 2021-07-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0002_steamaccount_steam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamaccount',
            name='session',
            field=models.FileField(default=None, editable=False, null=True, upload_to='sessions/'),
        ),
    ]
