# Generated by Django 3.2.2 on 2021-07-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('steam', '0004_auto_20210718_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamswap',
            name='node',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steam_swaps', to='management.swappernode'),
        ),
    ]
