# Generated by Django 3.2.2 on 2021-07-18 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_swappernode_max_threads'),
        ('steam', '0005_steamswap_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamswap',
            name='node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steam_swaps', to='management.swappernode'),
        ),
    ]
