# Generated by Django 3.2.2 on 2021-07-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0007_steamswap_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamswap',
            name='check_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='steamswap',
            name='last_checked',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
