# Generated by Django 3.2.2 on 2021-07-30 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0008_auto_20210729_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamswap',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
